openapi: 3.0.1
info:
  title: Todo Backend
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /todos:
    get:
      summary: Get the list of all Todos
      operationId: list
      responses:
        200:
          description: List of all Todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      operationId: add
      requestBody:
        description: The todo to create
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
            encoding:
              color:            # color=red,green,blue
                style: form
                explode: false
      parameters:
        - in: header
          name: HX-Request
          schema:
            type: boolean
          required: false
          description: Indicate that this is an htmx request. Should be set to 'true'.
      responses:
        201:
          description: The created Todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete the all todos that are completed
      operationId: todoDeleteCompleted
      responses:
        204:
          description: No content
    options:
      summary: Get the options
      operationId: todoOpt
      responses:
        200:
          description: OK
          content:
            application/json: {}
  /todos/{id}:
    get:
      summary: Get one todo
      operationId: todoGetOne
      parameters:
      - name: id
        in: path
        description: The id of the todo
        required: true
        schema:
          format: int64
          type: integer
        example: 42
      responses:
        200:
          description: The requested Todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete one todo
      operationId: delete
      parameters:
      - name: id
        in: path
        description: The id of the todo
        required: true
        schema:
          format: int64
          type: integer
        example: 42
      - in: header
        name: HX-Request
        schema:
          type: boolean
        required: false
        description: Indicate that this is an htmx request. Should be set to 'true'.
      responses:
        204:
          description: No content
    patch:
      summary: Update an existing todo
      operationId: edit
      parameters:
      - name: id
        in: path
        description: The id of the todo
        required: true
        schema:
          format: int64
          type: integer
        example: 42
      requestBody:
        description: The todo to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        200:
          description: The updated Todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
components:
  schemas:
    Todo:
      description: Object representing a Todo
      type: object
      properties:
        id:
          description: id of the entity
          format: int64
          type: integer
          example: 42
        title:
          description: title of the todo
          type: string
          example: My task
        completed:
          description: whether the todo is completed or not
          type: boolean
          example: false
        url:
          description: url associated with the todo
          type: string
        order:
          format: int32
          description: order in the priority list
          type: integer
          example: 10

